name: gmaj_dart_class
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  #// @dart=2.9
  # sdk: ">=2.11.0 <3.0.0"
  sdk: '>=2.14.4 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
